- type: job
  id: DeltaCommander
  name: job-name-delta-commander
  description: job-description-deltacommander
  playTimeTracker: JobDeltaCommander
  startingGear: DeltaCommanderGear
  icon: "JobIconDeltaCommander"
  supervisors: job-supervisors-field-commander
  canBeAntag: false
  access:
    - Maintenance
    - SquadDelta
    - SquadLeader
    - SquadSpecialist
    - Engineering
    - Command
    - Medical
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: DeltaCommanderGear
  equipment:
    eyes: ClothingEyesGlassesRPG
    jumpsuit: UGEJumpsuitSquadLeaderDelta
    id: DCommanderIDCard
    pocket1: EmergencyMedipen
    shoes: CMBootsBlack
