- type: job
  id: DeltaMarine
  name: job-name-delta-marine
  description: job-description-deltamarine
  playTimeTracker: JobDeltaMarine
  startingGear: DeltaMarineGear
  icon: "JobIconDeltaMarine"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - Maintenance
    - SquadDelta
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: DeltaMarineGear
  equipment:
    jumpsuit: UGEJumpsuitMarineDelta
    id: DRiflemanIDCard
    pocket1: EmergencyMedipen
