- type: job
  id: DeltaSpecialist
  name: job-name-delta-specialist
  description: job-description-deltaspecialist
  playTimeTracker: JobDeltaSpecialist
  startingGear: DeltaSpecialistGear
  icon: "JobIconDeltaSpecialist"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - Maintenance
    - SquadDelta
    - SquadSpecialist
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: DeltaSpecialistGear
  equipment:
    jumpsuit: UGEJumpsuitMarineDelta
    id: DSpecialistsIDCard
    pocket1: EmergencyMedipen
