- type: job
  id: CharlieEngineer
  name: job-name-charlie-engineer
  description: job-description-charlieengineer
  playTimeTracker: JobCharlieEngineer
  startingGear: CharlieEngineerGear
  icon: "JobIconCharlieEngineer"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - Maintenance
    - SquadCharlie
    - Engineering
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: CharlieEngineerGear
  equipment:
    jumpsuit: UGEJumpsuitEngineer
    id: CEngineerIDCard
    pocket1: EmergencyMedipen
