- type: job
  id: CharlieMedic
  name: job-name-charlie-medic
  description: job-description-charliemedic
  playTimeTracker: JobCharlieMedic
  startingGear: CharlieMedicGear
  icon: "JobIconCharlieMedic"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - Maintenance
    - SquadCharlieMedic
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: CharlieMedicGear
  equipment:
    jumpsuit: UGEJumpsuitMarineCharlie
    id: CMedicIDCard
    pocket1: EmergencyMedipen
