- type: job
  id: AlfaEngineer
  name: job-name-alfa-engineer
  description: job-description-alfaengineer
  playTimeTracker: JobAlfaEngineer
  startingGear: AlfaEngineerGear
  icon: "JobIconAlfaEngineer"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadAlpha
    - Maintenance
    - Engineering
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: AlfaEngineerGear
  equipment:
    jumpsuit: UGEJumpsuitEngineer
    id: AEngineerIDCard
    pocket1: EmergencyMedipen
