- type: job
  id: BravoCommander
  name: job-name-bravo-commander
  description: job-description-bravocommander
  playTimeTracker: JobBravoCommander
  startingGear: BravoCommanderGear
  icon: "JobIconBravoCommander"
  supervisors: job-supervisors-field-commander
  canBeAntag: false
  access:
    - SquadBravo
    - SquadLeader
    - SquadSpecialist
    - Engineering
    - Maintenance
    - Command
    - Medical
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: BravoCommanderGear
  equipment:
    jumpsuit: UGEJumpsuitSquadLeaderBravo
    eyes: ClothingEyesGlassesRPG
    id: BCommanderIDCard
    pocket1: EmergencyMedipen
    shoes: CMBootsBlack
