- type: job
  id: BravoMedic
  name: job-name-bravo-medic
  description: job-description-bravomedic
  playTimeTracker: JobBravoMedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMilitaryMedic
      time: 10800 # 3 hrs
  startingGear: BravoMedicGear
  icon: "JobIconBravoMedic"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - SquadBravoMedic
  special:
  - !type:AddComponentSpecial



- type: startingGear
  id: BravoMedicGear
  equipment:
    jumpsuit: UGEJumpsuitMarineBravo
    id: BMedicIDCard
    pocket1: EmergencyMedipen
