- type: job
  id: StaffOfficer
  name: Штаб офицер
  description: Связывать воедино весь корабль и подразделение, быть объектом ненависти, информировать капитана когда "Альфа" сделала кабум.
  playTimeTracker: JobStaffOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobMilitaryPoliceOfficer
      time: 3600 # 1 hrs
    - !type:RoleTimeRequirement
      role: JobSupplyOfficer
      time: 3600 # 1 hrs
    - !type:RoleTimeRequirement
      role: JobFieldCommander
      time: 3600 # 1 hrs
    - !type:DepartmentTimeRequirement
      department: CommandersGarrisons
      time: 3600 # 1 hrs
  startingGear: StaffOfficerGear
  icon: "JobIconStaffOfficer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - HeadOperations
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: StaffOfficerGear
  equipment:
    head: ClothingHeadCapOfficerWhite
    outerClothing: CMCoatSeniorOfficerWhite
    gloves: ClothingHandsField
    jumpsuit: UGEJumpsuitOfficerWhite
    eyes: ClothingEyesGlassesRPG
    id: StaffOfficerIDCard
    mask: CMMaskGasFieldСommander
    ears: ClothingHeadsetAltCommand
    back: ClothingBackpackSatchelLeather
    belt: ClothingBeltGermanОfficerHolsterGreen
    shoes: ClothingShoesBootsOldАrmy
    pocket1: RMCPouchLargeDrop
    pocket2: RMCPouchСommand
